In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing


In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width",500)


In [3]:
df = pd.read_csv('winequalityN.csv', low_memory=False)
df.head()


type  fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  alcohol  quality
0  white            7.0              0.27         0.36            20.7      0.045                 45.0                 170.0   1.0010  3.00       0.45      8.8        6
1  white            6.3              0.30         0.34             1.6      0.049                 14.0                 132.0   0.9940  3.30       0.49      9.5        6
2  white            8.1              0.28         0.40             6.9      0.050                 30.0                  97.0   0.9951  3.26       0.44     10.1        6
3  white            7.2              0.23         0.32             8.5      0.058                 47.0                 186.0   0.9956  3.19       0.40      9.9        6
4  white            7.2              0.23         0.32             8.5      0.058                 47.0                 186.0   0.9956  3.19       0.40      9.9        6

In [4]:
def check_dt(dataframe):
    print("SHAPE".center(70, "-"))
    print(dataframe.shape)
    print("TYPE".center(70, "-"))
    print(dataframe.dtypes)
    print("INFO".center(70, "-"))
    print(dataframe.info())
    print("NA".center(70, "-"))
    print(dataframe.isnull().sum())
    print("DESCRIBE".center(70, "-"))
    print(dataframe.describe().T)
    print("NUNIQUE".center(70, "-"))
    print(dataframe.nunique())
check_dt(df)


--------------------------------SHAPE---------------------------------
(6497, 13)
---------------------------------TYPE---------------------------------
type                     object
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object
---------------------------------INFO---------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non

In [5]:
type = df["type"].values
print(type)
type.shape


['white' 'white' 'white' ... 'red' 'red' 'red']


(6497,)

In [6]:
le = preprocessing.LabelEncoder()
type1 = le.fit_transform(df["type"])
type1 = pd.DataFrame(data=type1)
type1.columns=["type1"]
type1


type1
0         1
1         1
2         1
3         1
4         1
...     ...
6492      0
6493      0
6494      0
6495      0
6496      0

[6497 rows x 1 columns]

In [7]:
df1=pd.concat([df,type1],axis=1)
df1.drop("type",axis=1,inplace=True)
df1.head()


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  alcohol  quality  type1
0            7.0              0.27         0.36            20.7      0.045                 45.0                 170.0   1.0010  3.00       0.45      8.8        6      1
1            6.3              0.30         0.34             1.6      0.049                 14.0                 132.0   0.9940  3.30       0.49      9.5        6      1
2            8.1              0.28         0.40             6.9      0.050                 30.0                  97.0   0.9951  3.26       0.44     10.1        6      1
3            7.2              0.23         0.32             8.5      0.058                 47.0                 186.0   0.9956  3.19       0.40      9.9        6      1
4            7.2              0.23         0.32             8.5      0.058                 47.0                 186.0   0.9956  3.19       0.40      9.9        6      1

In [8]:
df1.dropna(inplace=True)
df1.isnull().sum()


fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
type1                   0
dtype: int64

In [9]:
x=df1.iloc[:,0:12].values
x.shape

(6463, 12)

In [10]:
y=df1.iloc[:,-1:].values
y.shape


(6463, 1)

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [12]:
pc=PCA(n_components=2)
X_train1=pc.fit_transform(X_train)
X_test1=pc.transform(X_test)


In [13]:
lr=LogisticRegression()
reg=lr.fit(X_train,y_train)
pred=lr.predict(X_test)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
reg1=lr.fit(X_train1,y_train)
pred1=lr.predict(X_test1)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
print('Actual / Not PCA')
cm=confusion_matrix(y_test,pred)
print(cm)


Actual / Not PCA
[[329   6]
 [  2 956]]


In [16]:
print('Actual / PCA')
cm1=confusion_matrix(y_test,pred1)
print(cm1)


Actual / PCA
[[322  13]
 [ 11 947]]


In [17]:
print("Not PCA / PCA")
cm2=confusion_matrix(pred,pred1)
print(cm2)


Not PCA / PCA
[[324   7]
 [  9 953]]
